### ISSUE TITLE
careplan ResourceType is null

### ISSUE THREAD

**Issue by kopai-bmk** [HMSConnect/hms-widget-sdk#36]
**Describe the bug**
request to 'careplan service' but resived schema with resourceType=null

**Comment by HMSConnect** [comment]
@kopai-bmk , thank you for the information.
**Could you show me more detail such as request URL(just only API endpoint)?**

Because I got expected return result, please refer to image below:
https://www.dropbox.com/s/c16hmotfqf5pd8s/careplan-schema-is-null.png?dl=0

**Or schema issue?**
After investigated, I found "organization" key in "careplan" schema but it is not associate with Gitbook ("organization" key not existing in the document). Please help confirm it. I will check our side too.

> **Describe the bug**
> request to 'careplan service' but resived schema with resourceType=null

**Comment by kopai-bmk** [comment]
from the image you attached above, I expect 'shema.resourceType' to be 'careplan'. (as I comment in the image link.)

**Comment by HMSConnect** [comment]
@kopai-bmk , you mean 'careplan' (case-sensitive), right?

In HMS data schema, we didn't provide that format. We just **provided only full name of the "resourceType"**.

**Comment by kopai-bmk** [comment]
from image below:
https://drive.google.com/file/d/1ceaO_4JT_4_lice53OMOBLSnNZ6ZjRgk/view?usp=sharing

resourceType in schema has a value of null instead of "careplan" or "Care Plan"

**Comment by HMSConnect** [comment]
@kopai-bmk , oh thank you for the highlight in the image, I'm mistake >,<. 
Let's me check.

**Comment by HMSConnect** [comment]
@kopai-bmk , I have fixed the issue on schema version "2.4.32". Please help check it again.
