### ISSUE TITLE
[Patient] Patient Search Result (Backend)

### ISSUE THREAD

**Issue by HMSConnect** [HMSConnect/hms-widget-sdk#6]

**Comment by tinnaratA** [comment]
In order to support Front-end search functionality, the back-end shall have below capability.

- Create NodeJS Integration Middleware it should be contained.

       - Restful Service integration between Front-end and back-end. (Router)
       - Proxy Layer is an integration layer between Front-End and Data Adapter
       - Data Adapters Factory Layer is an adapter to connect to SandBoxs or other data environments(DEV, QA, PROD, LOCAL).
- Restful path must be **start** with domain resource for example **/v1/patient?mrn=xxxxxx**
- Middleware should be supported GLOBAL environment $ENV_HOST$/v1/patient 
- Able to support multi-environment. server start LOCAL, PROD, DEV
- Class DIagram & Architect diagrams are required. Please using draw.io

**Comment by tinnaratA** [comment]
When connect to sandbox
Use Patient/a1f91f29-b0d7-4f4c-a530-b7719dfbd470
Use Encounter/3b8066d8-15fd-4687-9343-3eb48df24dcb to reference to other domain resources

**Comment by HMSConnect** [comment]
Done
